name: C/C++ CI with Timeout

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  timed-build-and-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libpthread-stubs0-dev
    - name: Compile the Program
      run: gcc -o df df.c -lpthread
    - name: Run the Program for 1 Minute
      run: timeout 60 ./df 6
